####################################################
# Server Side Up -  Docker Utility Image
#####################################################

FROM docker:dind

LABEL maintainer="Jay Rogers <jay@serversideup.net>"

# Install docker compose and set 
RUN apk add --no-cache docker-compose curl && rm -rf /var/cache/apk/*