name: Docker Publish

on:
  # When changes are pushed to the "main" branch, run it
  push:
    branches:
      - main

  # Run every day at 1200 UTC to update the images
  schedule:
    - cron: '0 12 * * *'

jobs:
  push:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      
      - id: compose
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          owner: docker
          repo: compose
          excludes: prerelease, draft

      - name: Build and tag image
        run: docker build utility/. --build-arg "COMPOSE_VERSION=${{ steps.compose.outputs.release }}" --tag serversideup/docker-utility

      - name: Push version image to DockerHub
        run: docker push serversideup/docker-utility

  update_container_readme:
    runs-on: ubuntu-latest
    name: Push README to Docker Hub
    steps:
      - name: git checkout
        uses: actions/checkout@v2
        with:
          ref: main

      - name: push README to Dockerhub
        uses: christian-korneck/update-container-description-action@v1
        env:
          DOCKER_USER: ${{ secrets.DOCKER_HUB_README_USERNAME }}
          DOCKER_PASS: ${{ secrets.DOCKER_HUB_README_PASSWORD }}
        with:
          destination_container_repo: serversideup/docker-utility
          provider: dockerhub
          short_description: 'A super small, but super powerful docker image for CI processes.'
          readme_file: 'README.md'